swagger: "2.0"
info:
  description: "Prueba de swagger para [tp](https://docs.google.com/document/d/11WHvRIowS8IFgWutqvhym93fZ39aRmPlqb8TJ_Nldg8/edit)."
  version: "1.0.0"
  title: "Swagger tp"
  contact:
    email: "brian.graj@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "cursos"
  description: "Everything about your cursos"
schemes:
- "http"
paths:
  /cursos:
    get:
      tags:
        - "cursos"
      summary: "Busca todos los cursos"
      description: "Se pueden filtrar por duracion y anio"
      operationId: "getCursos"
      produces:
        - "application/json"
      parameters:
        - name: "duracion"
          in: "query"
          description: "Duracion del curso"
          required: false
          type: "integer"
      responses:
        200:
          description: "Se obtuvieron los cursos"
          schema:
            $ref: "#/definitions/CursosResponse"
        500:
          description: "Error en el servidor"
    post:
      tags:
      - "cursos"
      summary: "Agrega un curso"
      description: ""
      operationId: "postCursos"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Curso a agregar"
        required: true
        schema:
          $ref: "#/definitions/Curso"
      responses:
        201:
          description: "El curso fue creado"
        500:
          description: "Error en el servidor"
  /cursos/{id}:
    get:
      tags:
      - "cursos"
      summary: "Busca un curso por id"
      operationId: "getCursoById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id del curso"
        required: true
        type: "string"
      responses:
        200:
          description: "Se obtuvo el curso"
          schema:
            $ref: "#/definitions/Curso"
        500:
          description: "Error en el servidor"
    delete:
      tags:
      - "cursos"
      summary: "Borrar un curso"
      operationId: "deleteCurso"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id del curso a borrar"
        required: true
        type: "string"
      responses:
        200:
          description: "Curso eliminado correctamente"
        500:
          description: "Error en el servidor"
  /cursos/{id}/alumnos:
    get:
      tags:
      - "cursos"
      summary: "Busca los alumnos de un curso"
      operationId: "getAlumnosDeCurso"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id del curso"
        required: true
        type: "string"
      responses:
        200:
          description: "Se obtuvieron los alumnos del curso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Alumno"
        500:
          description: "Error en el servidor"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Alumno:
    type: "object"
    properties:
      nombre:
        type: "string"
        example: "brian"
      apellido:
        type: "string"
        example: "graj"
      dni:
        type: "integer"
      direccion:
        type: "string"
        example: "calle 1"
      nota:
        type: "integer"
    xml:
      name: "Alumno"
  Curso:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      anioDictado:
        type: "integer"
      duracion:
        type: "integer"
      tema:
        type: "string"
        example: "bigData"
      alumnos:
        type: "array"
        xml:
          name: "curso"
          wrapped: true
        items:
          $ref: "#/definitions/Alumno"
    xml:
      name: "Curso"
  CursosResponse:
    type: "object"
    properties:
      code:
        type: "integer"
      message:
        type: "array"
        xml:
          name: "alumnos"
          wrapped: true
        items:
          $ref: "#/definitions/Alumno"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"